name: Format Check

on:
    push:
        branches:
            - 'main'
            - 'dev'
            - 'US**'
    pull_request:
        branches:
            - 'main'
            - 'dev'
            - 'US**'

permissions:
    contents: read

jobs:
    prettier:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: '20'
                  cache: npm
            - run: npm ci
            - run: npm run format-check
